CONFIG_DIR = "/config"
STATIC_DIR = "/static"
CONFIG_FILE = CONFIG_DIR + "/config.json"
UNIFIED_TIME_FORMAT = "%Y-%m-%d %H:%M"
VERSION_INFO = "0.9c"
HTML_TIME_FORMAT = "%Y-%m-%d\n%H:%M"
HTML_INPUT_TIME_FORMAT = "%Y-%m-%dT%H:%M"
DEBUG_MODE = False
EXPERIMENTAL = False
